### ISSUE TITLE
`postcss-preset-env` not working.

### ISSUE THREAD

**Issue by romainmenke** [veikkoeeva/openwc-miniflare#1]
https://github.com/veikkoeeva/openwc-miniflare/blob/b693dabaf6eb428d5fb0612e0203d548105edc84/rollup.config.js#L32-L43

```
    postcss({
      inject: true,
      minimize: true,
      modules: true,
      stage: 3,
      browsers: 'last 2 versions',
      features: {
        'lab-function': true,
        'nesting-rules': true,
        'color-mod-function': { unresolved: 'warn' }
      }
    }),
```

Should be something like this :

```
    postcss({
      inject: true,
      minimize: true,
      modules: true,
      plugins: [
        postcssPresetEnv({
          stage: 3,
          browsers: 'last 2 versions',
          features: {
            'lab-function': {
               preserve: true
             },
            'nesting-rules': true
          }
        })
      ]
    }),
```

-----------------

Currently it seems you are not passing any plugins to postcss.
So `postcss-preset-env` is not running.

`'color-mod-function'` was removed from `postcss-preset-env`
So can't be enabled this way.
The spec is dead so best to avoid this one.

`preserve: true` option must be used to have `lab` / `lch` preserved in CSS.
Without it you won't be able to go beyond the sRGB color profile.

⚠️ beware that any colors only available in `display-p3` will look very different.
There is an ongoing effort to handle this better. It's only recently been defined in the spec how to do this.

**Comment by romainmenke** [comment]
_Follow up_

It would be interesting to know what your current config was based on?
Maybe we can have better docs in `postcss-preset-env` to get people started.

**Comment by veikkoeeva** [comment]
@romainmenke Much appreciated, thank you!

Indeed, this was not my own set up from start to finnish (barring my own mistakes). It's from https://open-wc.org/ `npm init @open-wc`/ https://modern-web.dev/ with some modifications and adding https://workers.cloudflare.com/ infra.

I tried just a moment ago these modifications and I did not observe any change in the output. I have the added `styles.css` there to see if there are changes in either external stylesheets or inline styles. And now that I think about this, I think I should also add a similar case for the web components,

I have not kept books on the permutations I have cycled through, but I feel many I've tried, including this here now. The creators of the project frequent at https://open-wc.org/discover/slack/ (the link is also there, albeit a tad difficult to spot). Let I reach out them and ask about this case (I provide also this link). I think having PostCSS processing included in their template would be absolutely great! Albeit I also recognize I'm not on the hook maintaining these configurations, just consuming and trying to do "one more thing". :)

**Comment by romainmenke** [comment]
Correction, seems like `@web/rollup-plugin-html` is eating all the css.
So the `postcss` plugin in the rollup config never sees anything.

This might help :

https://modern-web.dev/docs/building/rollup-plugin-html/#transforming-html-files-and-assets


You could also see if it's possible to configure a step in your rollup config where it uses a wildcard to transform any `*.css` files in your dist folder and overrides the previous content.
